// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYRun2tvA0HdOFzCoDC1PUzsrFfC1tHKU',
    appId: '1:251424756609:web:0ebdf67480411d1cb84e80',
    messagingSenderId: '251424756609',
    projectId: 'route-optimization-474616',
    authDomain: 'route-optimization-474616.firebaseapp.com',
    storageBucket: 'route-optimization-474616.firebasestorage.app',
    measurementId: 'G-CQQT5DGJ4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnYfuErOr3NpRyxJGUNkxALlp330iWqFk',
    appId: '1:251424756609:android:f3642db243d93a73b84e80',
    messagingSenderId: '251424756609',
    projectId: 'route-optimization-474616',
    storageBucket: 'route-optimization-474616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhXkRXLFnTPMve3qzkwoY8GqxJMqGsDaA',
    appId: '1:251424756609:ios:91cccf17a12ccb3eb84e80',
    messagingSenderId: '251424756609',
    projectId: 'route-optimization-474616',
    storageBucket: 'route-optimization-474616.firebasestorage.app',
    iosClientId:
        '251424756609-cckrse8tpfd2m5lo16t8pemjh62mfok1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhXkRXLFnTPMve3qzkwoY8GqxJMqGsDaA',
    appId: '1:251424756609:ios:91cccf17a12ccb3eb84e80',
    messagingSenderId: '251424756609',
    projectId: 'route-optimization-474616',
    storageBucket: 'route-optimization-474616.firebasestorage.app',
    iosClientId:
        '251424756609-cckrse8tpfd2m5lo16t8pemjh62mfok1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYRun2tvA0HdOFzCoDC1PUzsrFfC1tHKU',
    appId: '1:251424756609:web:2b8365031171b101b84e80',
    messagingSenderId: '251424756609',
    projectId: 'route-optimization-474616',
    authDomain: 'route-optimization-474616.firebaseapp.com',
    storageBucket: 'route-optimization-474616.firebasestorage.app',
    measurementId: 'G-6VLDH3FZKL',
  );
}
